services:
  configurator:
    environment:
      PROJECT_CLONE_URL: https://github.com/dockersamples/labspace-ai-fundamentals

  workspace:
    image: dockersamples/labspace-workspace-node
    environment:
      OPENAI_BASE_URL: http://model-runner.docker.internal/engines/v1
      OPENAI_API_KEY: not-required
      OPENAI_MODEL: ai/llama3.2:3B-Q4_K_M

  visual-chatbot:
    image: mikesir87/visual-chatbot
    use_api_socket: true
    ports:
      - 3050:3000
    models:
      llama3:
        endpoint_var: OPENAI_BASE_URL
        model_var: OPENAI_MODEL

models:
  llama3:
    model: ai/llama3.2:3B-Q4_K_M
